In [122]:
import pandas as pd
import numpy as np

In [123]:
df = pd.read_csv('laptops.csv')

In [124]:
pd.__version__

'1.5.3'

In [125]:
len(df)

2160

In [126]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [127]:
df['Laptop'].nunique()

2160

In [128]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [129]:
max_price = df[df['Brand'] == 'Dell']['Final Price'].max()

In [130]:
max_price

3936.0

In [131]:
df['Screen'].median()

15.6

In [132]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [133]:
df.groupby('Screen').Screen.agg('count')

Screen
10.10       1
10.50       7
10.95       1
11.60      16
12.00       4
12.30      13
12.40       6
12.50       1
13.00      27
13.30     131
13.40      19
13.50      19
13.60      11
13.90       2
14.00     392
14.10      11
14.20      14
14.40       6
14.50       3
15.00      21
15.30       8
15.40       5
15.60    1009
16.00     174
16.10      48
16.20      10
17.00      33
17.30     161
18.00       3
Name: Screen, dtype: int64

In [134]:
df['Screen'] = df['Screen'].fillna(df['Screen'].mode)

In [135]:
df['Screen'].isna().sum()

0

In [136]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

     Screen Touch  Final Price  
0      15.6    No      1009.00  
1      15.6    No       299.00  
2      15.6    No       789.00  
3      15.6    No      1199.00  
4      15.6    No       669.01  
...     ...   ...          ...  
2155   17.3    No      2699.99  
2156   17.3    No      2899.99  
2157   17.3    No      3399.99  
2158   13.4   Yes      1899.99  
2159   13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [137]:
df [df['Model'] == 'Innjoo' ]

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [138]:
df[df['Brand']=="Innjoo"]

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN   15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN   15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN   14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN   14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN   14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN   14.1    No       431.38

In [139]:
df_new = df[df['Brand']=="Innjoo"]

In [140]:
df_new[['RAM', 'Storage', 'Screen']]

RAM  Storage Screen
1478    8      256   15.6
1479    8      512   15.6
1480    4       64   14.1
1481    6       64   14.1
1482    6      128   14.1
1483    6      128   14.1

In [141]:
X = df_new[['RAM', 'Storage', 'Screen']].to_numpy()

In [142]:
X

array([[8, 256, 15.6],
       [8, 512, 15.6],
       [4, 64, 14.1],
       [6, 64, 14.1],
       [6, 128, 14.1],
       [6, 128, 14.1]], dtype=object)

In [174]:
X_transpose = np.transpose(X)

In [175]:
X_transpose

array([[8, 8, 4, 6, 6, 6],
       [256, 512, 64, 64, 128, 128],
       [15.6, 15.6, 14.1, 14.1, 14.1, 14.1]], dtype=object)

In [191]:
XTX = np.matmul(X_transpose, X)

In [192]:
XTX

array([[252, 8320, 559.8000000000001],
       [8320, 368640, 17395.199999999997],
       [559.8000000000001, 17395.199999999997, 1281.9599999999998]],
      dtype=object)

In [195]:
XTX = np.array(XTX, dtype = 'float')

In [196]:
XTX_inv = np.linalg.inv(XTX)

In [197]:
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [198]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [199]:
res= np.matmul(XTX_inv, X_transpose)

In [200]:
res

array([[0.26298348937155747, -0.12560232682651673, -0.4064638893310435,
        0.1495868725310039, 0.05244041848148551, 0.05244041848148551],
       [-0.0011015526647083678, 0.002950587494754517,
        0.0012589173310952892, -0.0017769093579521672,
        -0.0007638743180864464, -0.0007638743180864464],
       [-0.0877222600058215, 0.026979096827303706, 0.17140891017633103,
        -0.03021080032091994, -0.0015354611126385809,
        -0.0015354611126385809]], dtype=object)

In [201]:
w = res * y

In [202]:
w.sum()

91.29988062995614