In [1]:
import numpy as np

# Vector operations

In [2]:
u = np.array([2,4,5,6])

In [3]:
v = np.array([1,2,3,4])

In [4]:
u*v

array([ 2,  8, 15, 24])

In [5]:
2*u*v

array([ 4, 16, 30, 48])

# Vector Vector Multiplication

In [6]:
print(u.shape[0])
print(v.shape[0])


4
4


In [7]:
z = np.array([1,2])

In [12]:
def vec_vec_mult(u,v):
    if v.shape[0]!= u.shape[0]:
        raise ValueError("Vectors must have the same shape")
    n = len(u)
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result


In [13]:
print(vec_vec_mult(u,v))

49.0


In [10]:
np.dot(u,v)

49

In [14]:
u.dot(v)

49

# Matrix Vector Multiplication


In [20]:
x = np.array([[2,4,5,6],
            [1,2,1,2],
            [3,1,2,1]])

In [26]:
x.shape[1]

4

In [24]:
y.shape[0]

4

In [21]:
y = np.array([1,2,3,4])

In [36]:
x.shape[0]

3

In [44]:
def mat_vec_mult(x,y):
    if x.shape[1] != y.shape[0]:
        raise ValueError("Matrix columns must match vector length")
    num_rows = x.shape[0]
    num_col = y.shape[0] #number of rows in matrix is equal to number of columns in vector
    result = np.zeros(num_rows)
    for i in range(num_rows):
        for j in range(num_col):
            result[i] += x[i][j] * y[j]
    return result
    

In [45]:
print(mat_vec_mult(x,y))

[49. 16. 15.]


In [47]:
np.dot(x,y)

array([49, 16, 15])

# Matrix Multiplication

In [75]:
def mat_mult(A,B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix A columns must match matrix B columns length")
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    
    result = np.zeros([rows_A, cols_B])
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
    return result
    
    
    

In [74]:
A = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
B = np.array([[2,3,4],
            [1,5,6],
             [4,5,6]])

In [76]:
B.shape[0]

3

In [77]:
print(mat_mult(A,B))

[[ 16.  28.  34.]
 [ 37.  67.  82.]
 [ 58. 106. 130.]]


In [78]:
np.dot(A,B)

array([[ 16,  28,  34],
       [ 37,  67,  82],
       [ 58, 106, 130]])

# Identity Matrix

In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])